export const SAMPLE_WORK = [
  {
    id: 'living-warm',
    title: 'Living Room — Warm Linen Finish',
    category: 'Interior Painting',
    location: 'Nashik',
    image: '/images/portfolio/sample-living-warm.webp',
    alt: 'Warm linen matte finish on living room walls in Nashik home',
  },
  {
    id: 'dining-accent',
    title: 'Dining Space — Terracotta Accent',
    category: 'Wall Design',
    location: 'Panchavati, Nashik',
    image: '/images/portfolio/sample-dining-accent.webp',
    alt: 'Terracotta accent wall with premium dining room paint finish',
  },
  {
    id: 'bedroom-calm',
    title: 'Master Bedroom — Soft Ivory Coat',
    category: 'Colour Consultation',
    location: 'Gangapur, Nashik',
    image: '/images/portfolio/sample-bedroom-calm.webp',
    alt: 'Calm ivory bedroom walls with expert colour coordination',
  },
  {
    id: 'kitchen-finish',
    title: 'Kitchen & Utility — Moisture Shield',
    category: 'Interior Painting',
    location: 'CIDCO, Nashik',
    image: '/images/portfolio/sample-kitchen-finish.webp',
    alt: 'Kitchen walls with moisture-resistant premium paint coating',
  },
  {
    id: 'office-commercial',
    title: 'Office Interior — Brand Palette',
    category: 'Commercial Painting',
    location: 'Satpur, Nashik',
    image: '/images/portfolio/sample-office-commercial.webp',
    alt: 'Commercial office interior with coordinated brand colour palette',
  },
  {
    id: 'exterior-villa',
    title: 'Villa Exterior — Weather Guard',
    category: 'Exterior Painting',
    location: 'Nashik',
    image: '/images/portfolio/sample-exterior-villa.webp',
    alt: 'Villa exterior repainted with durable weather-resistant coating',
  },
  {
    id: 'texture-wall',
    title: 'Feature Wall — Texture Finish',
    category: 'Texture Finishes',
    location: 'Deolali, Nashik',
    image: '/images/portfolio/sample-texture-wall.webp',
    alt: 'Decorative texture finish feature wall in modern interior',
  },
  {
    id: 'hallway-premium',
    title: 'Hallway & Entry — Premium Matte',
    category: 'Turnkey Execution',
    location: 'Nashik Road',
    image: '/images/portfolio/sample-hallway-premium.webp',
    alt: 'Hallway and entry painted with premium matte finish',
  },
  {
    id: 'accent-feature',
    title: 'Exterior Facade — Full Refresh',
    category: 'Exterior Painting',
    location: 'Sinnar, Nashik',
    image: '/images/portfolio/sample-accent-feature.webp',
    alt: 'Home exterior facade with fresh premium paint application',
  },
  {
    id: 'bathroom-spa',
    title: 'Ensuite Bathroom — Spa White Finish',
    category: 'Waterproofing',
    location: 'Panchavati, Nashik',
    image: '/images/portfolio/sample-bathroom-spa.webp',
    alt: 'Bathroom walls with moisture-proof spa white paint finish',
  },
  {
    id: 'lounge-luxury',
    title: 'Premium Lounge — Layered Neutrals',
    category: 'Interior Painting',
    location: 'Nashik',
    image: '/images/portfolio/sample-lounge-luxury.webp',
    alt: 'Luxury lounge interior with layered neutral wall colours',
  },
] as const

export type SampleWorkItem = (typeof SAMPLE_WORK)[number]
